export default {
    SET_PLAYER_LOOKS: 'SET_PLAYER_LOOKS',
    SET_PLAYER_NAME: 'SET_PLAYER_NAME',
    SET_LOCATION_DATA: 'SET_LOCATION_DATA',
    SET_SCENE_DATA: 'SET_SCENE_DATA',
    SET_ITEM_DATA: 'SET_ITEM_DATA',
    SET_CONTAINER_DATA: 'SET_CONTAINER_DATA',
    SHOW_CHARACTER_PANE: 'SHOW_CHARACTER_PANE',
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    EXIT_CONTAINER: 'EXIT_CONTAINER',
    RETURN_TO_GAME: 'RETURN_TO_GAME',
    USER_ACT_NEXT_SCENE: 'USER_ACT_NEXT_SCENE',
    USER_ACT_LOOT: 'USER_ACT_LOOT',
};